server:
    port: 8081
spring:
    cloud:
        gcp:
            project-id: ${PROJECT_ID}
            pubsub:
                emulator-host: localhost:8085
    devtools:
        restart:
            enabled: true

feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: full

br:
    com:
        bullla:
            business-client:
                url: ${BULLLA_BUSINESS_CLIENT_MS_URL}